name: #PROJECT_NAME#
packages:
  # Uncomment this to add SPM dependency
  # ReSwift:
  #   url: https://github.com/ReSwift/ReSwift.git
  #   branch: 5.0.0
targets:
  #PROJECT_NAME#:
    type: application
    platform: iOS
    deploymentTarget: 14.0
    sources: [iOS, Shared]
    # dependencies:
    #   - package: ReSwift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ak.#PROJECT_NAME#
      SWIFT_VERSION: '5.3'
    postCompileScripts:
      - script: |
          if mint list | grep -q 'SwiftLint'; then
          mint run SwiftLint swiftlint autocorrect
          mint run SwiftLint swiftlint
          else
          echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        name: Swiftlint
  #PROJECT_NAME#Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: '14.0'
    sources: [Tests]
    dependencies:
      - target: #PROJECT_NAME#
